### PR TITLE
adding big update with tokens and fixing forking while NULL

### PR DESCRIPTION
**Pull request by nuketayev**
pzdc zaebalsya

### CODE REVIEW

**Comment by nuketayev** [comment]
basically all base done, now its replacing some functions from execute_command, because it contains commands from libraries and some are not allowed. Please implement with your functions like get_command_path. I didn't wanted to spend time to study your implementation, so execute_command function was made by gpt for testing purposes if it works. It does work, now we have implement the build ins and minor things

**Comment by nuketayev** [comment]
pull akzholbranch and review and test, I can explain on a call. Because from github reviewer might be a lot to keep in mind all changes

**Comment by nuketayev** [comment]
enums are good! Now I have a clear understanding; before always was confusing a bit

**Comment by gharazka** [comment]
Will test more later, approved for now

**Comment by nuketayev** [comment]
so merge?

**Comment by nuketayev** [comment]
merge it then

**Comment by gharazka** [comment]
Mallocing too much memory for tokens for now, let's change array of tokens to be a linked list

**Pull request merged**
